### ISSUE TITLE
登陆后接收不到消息 log出这个 unknown PbGetMsg type 732

### ISSUE THREAD

**Issue by tghjnjvg** [mamoe/mirai-demos#11]
登陆后接收不到消息 log出这个 unknown PbGetMsg type 732

**Comment by tghjnjvg** [comment]
```
05-04 09:40:02.779 9847-10044/net.mamoe.mirai.demo I/System.out: [96mNetwork(778162278) 09:40:02 : unknown PbGetMsg type 732
05-04 09:40:02.780 9847-10044/net.mamoe.mirai.demo I/System.out: [96mNetwork(778162278) 09:40:02 : unknown PbGetMsg type 732
05-04 09:40:02.780 9847-10044/net.mamoe.mirai.demo I/System.out: [96mNetwork(778162278) 09:40:02 : unknown PbGetMsg type 732
05-04 09:40:02.780 9847-10044/net.mamoe.mirai.demo I/System.out: [96mNetwork(778162278) 09:40:02 : unknown PbGetMsg type 732
05-04 09:40:02.780 9847-10044/net.mamoe.mirai.demo I/System.out: [96mNetwork(778162278) 09:40:02 : unknown PbGetMsg type 732
05-04 09:40:02.780 9847-10044/net.mamoe.mirai.demo I/System.out: [96mNetwork(778162278) 09:40:02 : unknown PbGetMsg type 732
05-04 09:40:02.781 9847-10044/net.mamoe.mirai.demo I/System.out: [96mNetwork(778162278) 09:40:02 : unknown PbGetMsg type 732
05-04 09:40:02.781 9847-10044/net.mamoe.mirai.demo I/System.out: [96mNetwork(778162278) 09:40:02 : unknown PbGetMsg type 732
05-04 09:40:02.781 9847-10044/net.mamoe.mirai.demo I/System.out: [96mNetwork(778162278) 09:40:02 : unknown PbGetMsg type 732
05-04 09:40:02.781 9847-10044/net.mamoe.mirai.demo I/System.out: [96mNetwork(778162278) 09:40:02 : unknown PbGetMsg type 732
05-04 09:40:02.781 9847-10044/net.mamoe.mirai.demo I/System.out: [96mNetwork(778162278) 09:40:02 : unknown PbGetMsg type 732
05-04 09:40:02.781 9847-10044/net.mamoe.mirai.demo I/System.out: [96mNetwork(778162278) 09:40:02 : unknown PbGetMsg type 732
05-04 09:40:02.782 9847-10044/net.mamoe.mirai.demo I/System.out: [96mNetwork(778162278) 09:40:02 : unknown PbGetMsg type 732
05-04 09:40:02.782 9847-10044/net.mamoe.mirai.demo I/System.out: [96mNetwork(778162278) 09:40:02 : unknown PbGetMsg type 732
05-04 09:40:02.782 9847-10044/net.mamoe.mirai.demo I/System.out: [96mNetwork(778162278) 09:40:02 : unknown PbGetMsg type 732
05-04 09:40:02.782 9847-10044/net.mamoe.mirai.demo I/System.out: [96mNetwork(778162278) 09:40:02 : unknown PbGetMsg type 732
05-04 09:40:02.782 9847-10044/net.mamoe.mirai.demo I/System.out: [96mNetwork(778162278) 09:40:02 : unknown PbGetMsg type 732
05-04 09:40:02.783 9847-10044/net.mamoe.mirai.demo I/System.out: [96mNetwork(778162278) 09:40:02 : unknown PbGetMsg type 732
05-04 09:40:02.783 9847-10044/net.mamoe.mirai.demo I/System.out: [96mNetwork(778162278) 09:40:02 : unknown PbGetMsg type 732
05-04 09:40:02.783 9847-10044/net.mamoe.mirai.demo I/System.out: [96mNetwork(778162278) 09:40:02 : unknown PbGetMsg type 732
05-04 09:40:02.783 9847-10044/net.mamoe.mirai.demo I/System.out: [96mNetwork(778162278) 09:40:02 : unknown PbGetMsg type 732
05-04 09:40:02.783 9847-10044/net.mamoe.mirai.demo I/System.out: [96mNetwork(778162278) 09:40:02 : unknown PbGetMsg type 732
05-04 09:40:02.784 9847-10044/net.mamoe.mirai.demo I/System.out: [96mNetwork(778162278) 09:40:02 : unknown PbGetMsg type 732
05-04 09:40:02.784 9847-10044/net.mamoe.mirai.demo I/System.out: [96mNetwork(778162278) 09:40:02 : unknown PbGetMsg type 732
05-04 09:40:02.784 9847-10044/net.mamoe.mirai.demo I/System.out: [96mNetwork(778162278) 09:40:02 : unknown PbGetMsg type 732
05-04 09:40:02.784 9847-10044/net.mamoe.mirai.demo I/System.out: [96mNetwork(778162278) 09:40:02 : unknown PbGetMsg type 732
05-04 09:40:02.784 9847-10044/net.mamoe.mirai.demo I/System.out: [96mNetwork(778162278) 09:40:02 : unknown PbGetMsg type 732
05-04 09:40:02.785 9847-10044/net.mamoe.mirai.demo I/System.out: [96mNetwork(778162278) 09:40:02 : unknown PbGetMsg type 732
05-04 09:40:02.785 9847-10044/net.mamoe.mirai.demo I/System.out: [96mNetwork(778162278) 09:40:02 : unknown PbGetMsg type 732
05-04 09:40:02.785 9847-10044/net.mamoe.mirai.demo I/System.out: [96mNetwork(778162278) 09:40:02 : unknown PbGetMsg type 732
05-04 09:40:02.785 9847-10044/net.mamoe.mirai.demo I/System.out: [96mNetwork(778162278) 09:40:02 : unknown PbGetMsg type 732
05-04 09:40:02.785 9847-10044/net.mamoe.mirai.demo I/System.out: [96mNetwork(778162278) 09:40:02 : unknown PbGetMsg type 732
05-04 09:40:02.785 9847-10044/net.mamoe.mirai.demo I/System.out: [96mNetwork(778162278) 09:40:02 : unknown PbGetMsg type 732
05-04 09:40:02.786 9847-10044/net.mamoe.mirai.demo I/System.out: [96mNetwork(778162278) 09:40:02 : unknown PbGetMsg type 732
05-04 09:40:02.786 9847-10044/net.mamoe.mirai.demo I/System.out: [96mNetwork(778162278) 09:40:02 : unknown PbGetMsg type 732
05-04 09:40:02.786 9847-10044/net.mamoe.mirai.demo I/System.out: [96mNetwork(778162278) 09:40:02 : unknown PbGetMsg type 732
05-04 09:40:02.786 9847-10044/net.mamoe.mirai.demo I/System.out: [96mNetwork(778162278) 09:40:02 : unknown PbGetMsg type 732
05-04 09:40:02.786 9847-10044/net.mamoe.mirai.demo I/System.out: [96mNetwork(778162278) 09:40:02 : unknown PbGetMsg type 732
05-04 09:40:02.786 9847-10044/net.mamoe.mirai.demo I/System.out: [96mNetwork(778162278) 09:40:02 : unknown PbGetMsg type 732
05-04 09:40:02.787 9847-10044/net.mamoe.mirai.demo I/System.out: [96mNetwork(778162278) 09:40:02 : unknown PbGetMsg type 732
05-04 09:40:02.787 9847-10044/net.mamoe.mirai.demo I/System.out: [96mNetwork(778162278) 09:40:02 : unknown PbGetMsg type 732
05-04 09:40:02.787 9847-10044/net.mamoe.mirai.demo I/System.out: [96mNetwork(778162278) 09:40:02 : unknown PbGetMsg type 732
05-04 09:40:02.787 9847-10044/net.mamoe.mirai.demo I/System.out: [96mNetwork(778162278) 09:40:02 : unknown PbGetMsg type 732
05-04 09:40:02.787 9847-10044/net.mamoe.mirai.demo I/System.out: [96mNetwork(778162278) 09:40:02 : unknown PbGetMsg type 732
05-04 09:40:02.788 9847-10044/net.mamoe.mirai.demo I/System.out: [96mNetwork(778162278) 09:40:02 : unknown PbGetMsg type 732
05-04 09:40:02.788 9847-10044/net.mamoe.mirai.demo I/System.out: [96mNetwork(778162278) 09:40:02 : unknown PbGetMsg type 732
05-04 09:40:02.788 9847-10044/net.mamoe.mirai.demo I/System.out: [96mNetwork(778162278) 09:40:02 : unknown PbGetMsg type 732
05-04 09:40:02.788 9847-10044/net.mamoe.mirai.demo I/System.out: [96mNetwork(778162278) 09:40:02 : unknown PbGetMsg type 732
05-04 09:40:02.788 9847-10044/net.mamoe.mirai.demo I/System.out: [96mNetwork(778162278) 09:40:02 : unknown PbGetMsg type 732
05-04 09:40:02.788 9847-10044/net.mamoe.mirai.demo I/System.out: [96mNetwork(778162278) 09:40:02 : unknown PbGetMsg type 732
05-04 09:40:02.789 9847-10044/net.mamoe.mirai.demo I/System.out: [96mNetwork(778162278) 09:40:02 : unknown PbGetMsg type 732
05-04 09:40:02.789 9847-10044/net.mamoe.mirai.demo I/System.out: [96mNetwork(778162278) 09:40:02 : unknown PbGetMsg type 732
05-04 09:40:02.789 9847-10044/net.mamoe.mirai.demo I/System.out: [0mNetwork(778162278) 09:40:02 : Packet: MessageSvc.PbGetMsg.Response(syncFlagFromServer=CONTINUE, messages=<Iterable>))
05-04 09:40:02.791 9847-10030/net.mamoe.mirai.demo I/System.out: [0mNetwork(778162278) 09:40:02 : Send: MessageSvc.PbGetMsg
05-04 09:40:02.899 9847-10030/net.mamoe.mirai.demo I/System.out: [0mNetwork(778162278) 09:40:02 : Send: MessageSvc.PbDeleteMsg
05-04 09:40:02.901 9847-10030/net.mamoe.mirai.demo I/System.out: [96mNetwork(778162278) 09:40:02 : unknown PbGetMsg type 732
05-04 09:40:02.902 9847-10030/net.mamoe.mirai.demo I/System.out: [96mNetwork(778162278) 09:40:02 : unknown PbGetMsg type 732
05-04 09:40:02.902 9847-10030/net.mamoe.mirai.demo I/System.out: [96mNetwork(778162278) 09:40:02 : unknown PbGetMsg type 732
05-04 09:40:02.903 9847-10030/net.mamoe.mirai.demo I/System.out: [96mNetwork(778162278) 09:40:02 : unknown PbGetMsg type 732
05-04 09:40:02.904 9847-10030/net.mamoe.mirai.demo I/System.out: [96mNetwork(778162278) 09:40:02 : unknown PbGetMsg type 732
05-04 09:40:02.904 9847-10030/net.mamoe.mirai.demo I/System.out: [96mNetwork(778162278) 09:40:02 : unknown PbGetMsg type 732
05-04 09:40:02.905 9847-10030/net.mamoe.mirai.demo I/System.out: [96mNetwork(778162278) 09:40:02 : unknown PbGetMsg type 732
05-04 09:40:02.906 9847-10030/net.mamoe.mirai.demo I/System.out: [96mNetwork(778162278) 09:40:02 : unknown PbGetMsg type 528
05-04 09:40:02.906 9847-10030/net.mamoe.mirai.demo I/System.out: [96mNetwork(778162278) 09:40:02 : unknown PbGetMsg type 732
05-04 09:40:02.907 9847-10030/net.mamoe.mirai.demo I/System.out: [96mNetwork(778162278) 09:40:02 : unknown PbGetMsg type 732
05-04 09:40:02.907 9847-10030/net.mamoe.mirai.demo I/System.out: [96mNetwork(778162278) 09:40:02 : unknown PbGetMsg type 732
05-04 09:40:02.908 9847-10030/net.mamoe.mirai.demo I/System.out: [96mNetwork(778162278) 09:40:02 : unknown PbGetMsg type 732
05-04 09:40:02.908 9847-10030/net.mamoe.mirai.demo I/System.out: [96mNetwork(778162278) 09:40:02 : unknown PbGetMsg type 732
05-04 09:40:02.909 9847-10030/net.mamoe.mirai.demo I/System.out: [96mNetwork(778162278) 09:40:02 : unknown PbGetMsg type 732
05-04 09:40:02.909 9847-10030/net.mamoe.mirai.demo I/System.out: [96mNetwork(778162278) 09:40:02 : unknown PbGetMsg type 732
05-04 09:40:02.912 9847-10008/net.mamoe.mirai.demo I/System.out: [92mNetwork(778162278) 09:40:02 : Syncing friend message history: Success
05-04 09:40:02.926 9847-10008/net.mamoe.mirai.demo I/System.out: [92mBot(778162278) 09:40:02 : Login successful
05-04 09:40:02.992 9847-9847/net.mamoe.mirai.demo W/IInputConnectionWrapper: finishComposingText on inactive InputConnection
05-04 09:40:03.048 9847-9857/net.mamoe.mirai.demo I/art: Background partial concurrent mark sweep GC freed 208214(7MB) AllocSpace objects, 23(476KB) LOS objects, 9% free, 36MB/40MB, paused 1.117ms total 155.500ms
05-04 09:40:11.508 9847-10008/net.mamoe.mirai.demo I/System.out: [92mNetwork(778162278) 09:40:11 : Missing ConfigPushSvc.PushReq.
05-04 09:40:38.008 9847-10030/net.mamoe.mirai.demo I/System.out: [96mNetwork(778162278) 09:40:38 : unknown group 528 type 0x0000000000000115, data: 08 92 9A F4 8D 07 10 E6 A0 87 F3 02 1A 29 08 00 10 05 18 95 E5 BD F5 05 20 01 28 FF FF FF FF 0F 32 15 E5 AF B9 E6 96 B9 E6 AD A3 E5 9C A8 E8 BE 93 E5 85 A5 2E 2E 2E
05-04 09:40:38.009 9847-10030/net.mamoe.mirai.demo I/System.out: [0mNetwork(778162278) 09:40:38 : Packet: OnlinePush.ReqPush.Response
05-04 09:40:38.017 9847-10030/net.mamoe.mirai.demo I/System.out: [0mNetwork(778162278) 09:40:38 : Send: OnlinePush.RespPush
05-04 09:40:38.177 9847-10008/net.mamoe.mirai.demo I/System.out: [96mNetwork(778162278) 09:40:38 : unknown group 528 type 0x0000000000000115, data: 08 92 9A F4 8D 07 10 E6 A0 87 F3 02 1A 14 08 00 10 05 18 95 E5 BD F5 05 20 02 28 FF FF FF FF 0F 32 00
05-04 09:40:38.179 9847-10008/net.mamoe.mirai.demo I/System.out: [0mNetwork(778162278) 09:40:38 : Packet: OnlinePush.ReqPush.Response
05-04 09:40:38.187 9847-10008/net.mamoe.mirai.demo I/System.out: [0mNetwork(778162278) 09:40:38 : Send: OnlinePush.RespPush
05-04 09:40:38.202 9847-10030/net.mamoe.mirai.demo I/System.out: [0mNetwork(778162278) 09:40:38 : Packet: net.mamoe.mirai.qqandroid.network.protocol.data.jce.RequestPushNotify@cc9f25d
05-04 09:40:38.205 9847-10030/net.mamoe.mirai.demo I/System.out: [0mNetwork(778162278) 09:40:38 : Send: MessageSvc.PbGetMsg
05-04 09:40:38.304 9847-10008/net.mamoe.mirai.demo I/System.out: [0mNetwork(778162278) 09:40:38 : Send: MessageSvc.PbDeleteMsg
05-04 09:40:38.326 9847-10008/net.mamoe.mirai.demo I/System.out: [0mBot(778162278) 09:40:38 : Internet ferensic docter(1908215058) -> [mirai:source:30502,1094001068]zm
05-04 09:40:42.997 9847-10008/net.mamoe.mirai.demo I/System.out: [96mNetwork(778162278) 09:40:42 : unknown group 528 type 0x0000000000000115, data: 08 92 9A F4 8D 07 10 E6 A0 87 F3 02 1A 29 08 00 10 05 18 9A E5 BD F5 05 20 01 28 FF FF FF FF 0F 32 15 E5 AF B9 E6 96 B9 E6 AD A3 E5 9C A8 E8 BE 93 E5 85 A5 2E 2E 2E
05-04 09:40:42.998 9847-10008/net.mamoe.mirai.demo I/System.out: [0mNetwork(778162278) 09:40:42 : Packet: OnlinePush.ReqPush.Response
05-04 09:40:43.003 9847-10008/net.mamoe.mirai.demo I/System.out: [0mNetwork(778162278) 09:40:43 : Send: OnlinePush.RespPush
05-04 09:40:43.901 9847-10008/net.mamoe.mirai.demo I/System.out: [96mNetwork(778162278) 09:40:43 : unknown group 528 type 0x0000000000000115, data: 08 92 9A F4 8D 07 10 E6 A0 87 F3 02 1A 14 08 00 10 05 18 9B E5 BD F5 05 20 02 28 FF FF FF FF 0F 32 00
05-04 09:40:43.903 9847-10008/net.mamoe.mirai.demo I/System.out: [0mNetwork(778162278) 09:40:43 : Packet: OnlinePush.ReqPush.Response
05-04 09:40:43.910 9847-10008/net.mamoe.mirai.demo I/System.out: [0mNetwork(778162278) 09:40:43 : Send: OnlinePush.RespPush
05-04 09:40:43.965 9847-10008/net.mamoe.mirai.demo I/System.out: [0mNetwork(778162278) 09:40:43 : Packet: net.mamoe.mirai.qqandroid.network.protocol.data.jce.RequestPushNotify@47445cc
05-04 09:40:43.967 9847-10008/net.mamoe.mirai.demo I/System.out: [0mNetwork(778162278) 09:40:43 : Send: MessageSvc.PbGetMsg
05-04 09:40:44.070 9847-10030/net.mamoe.mirai.demo I/System.out: [0mNetwork(778162278) 09:40:44 : Send: MessageSvc.PbDeleteMsg
05-04 09:40:44.075 9847-10008/net.mamoe.mirai.demo I/System.out: [0mBot(778162278) 09:40:44 : Internet ferensic docter(1908215058) -> [mirai:source:30503,1194991235]zm
05-04 09:40:46.246 9847-10044/net.mamoe.mirai.demo I/System.out: [0mNetwork(778162278) 09:40:46 : Packet: OnlinePush.ReqPush.Response
05-04 09:40:46.255 9847-10044/net.mamoe.mirai.demo I/System.out: [0mNetwork(778162278) 09:40:46 : Send: OnlinePush.RespPush
05-04 09:40:46.939 9847-10010/net.mamoe.mirai.demo I/System.out: [0mNetwork(778162278) 09:40:46 : Packet: OnlinePush.ReqPush.Response
05-04 09:40:46.947 9847-10010/net.mamoe.mirai.demo I/System.out: [0mNetwork(778162278) 09:40:46 : Send: OnlinePush.RespPush
05-04 09:40:49.843 9847-10030/net.mamoe.mirai.demo I/System.out: [0mNetwork(778162278) 09:40:49 : Send: Heartbeat.Alive
05-04 09:40:49.895 9847-10030/net.mamoe.mirai.demo I/System.out: [0mNetwork(778162278) 09:40:49 : Packet: Heartbeat.Alive.Response
05-04 09:40:52.081 9847-10010/net.mamoe.mirai.demo I/System.out: [0mNetwork(778162278) 09:40:52 : Packet: OnlinePush.ReqPush.Response
05-04 09:40:52.087 9847-10010/net.mamoe.mirai.demo I/System.out: [0mNetwork(778162278) 09:40:52 : Send: OnlinePush.RespPush
05-04 09:40:52.211 9847-10010/net.mamoe.mirai.demo I/System.out: [0mNetwork(778162278) 09:40:52 : Packet: OnlinePush.ReqPush.Response
05-04 09:40:52.218 9847-10010/net.mamoe.mirai.demo I/System.out: [0mNetwork(778162278) 09:40:52 : Send: OnlinePush.RespPush
05-04 09:41:49.902 9847-10044/net.mamoe.mirai.demo I/System.out: [0mNetwork(778162278) 09:41:49 : Send: Heartbeat.Alive
05-04 09:41:49.955 9847-10044/net.mamoe.mirai.demo I/System.out: [0mNetwork(778162278) 09:41:49 : Packet: Heartbeat.Alive.Response
```

**Comment by tghjnjvg** [comment]
```
05-04 09:43:45.743 10096-10166/net.mamoe.mirai.demo W/System.err: java.io.EOFException: Not enough data in packet (1) to read 4 byte(s)
05-04 09:43:45.744 10096-10166/net.mamoe.mirai.demo W/System.err:     at kotlinx.io.core.ByteReadPacketBase.notEnoughBytesAvailable(Packet.kt:675)
05-04 09:43:45.744 10096-10166/net.mamoe.mirai.demo W/System.err:     at kotlinx.io.core.ByteReadPacketBase.access$notEnoughBytesAvailable(Packet.kt:15)
05-04 09:43:45.744 10096-10166/net.mamoe.mirai.demo W/System.err:     at kotlinx.io.core.ByteReadPacketBase.readIntSlow(Packet.kt:989)
05-04 09:43:45.744 10096-10166/net.mamoe.mirai.demo W/System.err:     at kotlinx.io.core.ByteReadPacketBase.readInt(Packet.kt:201)
05-04 09:43:45.744 10096-10166/net.mamoe.mirai.demo W/System.err:     at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler.processPacket(QQAndroidBotNetworkHandler.kt:557)
05-04 09:43:45.744 10096-10166/net.mamoe.mirai.demo W/System.err:     at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler.access$processPacket(QQAndroidBotNetworkHandler.kt:53)
05-04 09:43:45.744 10096-10166/net.mamoe.mirai.demo W/System.err:     at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler$startPacketReceiverJobOrKill$2.invokeSuspend(QQAndroidBotNetworkHandler.kt:91)
05-04 09:43:45.744 10096-10166/net.mamoe.mirai.demo W/System.err:     at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
05-04 09:43:45.744 10096-10166/net.mamoe.mirai.demo W/System.err:     at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
05-04 09:43:45.744 10096-10166/net.mamoe.mirai.demo W/System.err:     at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
05-04 09:43:45.744 10096-10166/net.mamoe.mirai.demo W/System.err:     at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
05-04 09:43:45.744 10096-10166/net.mamoe.mirai.demo W/System.err:     at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
05-04 09:43:45.744 10096-10166/net.mamoe.mirai.demo W/System.err:     at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```

**Comment by Him188** [comment]
请提供以下信息：
- 服务器在国内还是国外
- 群消息是否正常接收
- 是否能解析事件（任何）

**Comment by Him188** [comment]
> Internet ferensic docter(1908215058) -> [mirai:source:30503,1194991235]zm

这里不是可以正常接收吗

**Comment by a62082582** [comment]
我也同样出现上述问题，在群组聊天中，可以正常回复消息，但是私聊时偶尔就会出现问题，报错 unknown group 528 type 0x0000000000000115。这个问题在重启mirai后可以解决，但是一段时间后又再次出现。
