### ISSUE TITLE
java.lang.IllegalArgumentException: argument type mismatch

### ISSUE THREAD

**Issue by Icecoke-ops** [mamoe/mirai-demos#20]
我执行了项目中BlockingTest.java那个文件，发生了一下异常
```
2020-07-18 09:35:16 E/Bot 498861397: An exception was thrown under a coroutine of Bot
java.lang.IllegalArgumentException: argument type mismatch
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at net.mamoe.mirai.event.Events__JvmMethodListenersKt$registerEvent$15$1.invokeSuspend(JvmMethodListeners.kt:368)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```
mirai-core-1.1.3

**Comment by niehaiyang** [comment]
我也是这个问题呢，在接收群消息的时候，消息会正常打印，但是后面会跟这个报错。

**Comment by Him188** [comment]
使用 1.2.2 版本
